### ISSUE TITLE
Meteor methods with client stubs not supported for waitOn()? Promise not resolved Error: Can't set timers inside simulations

### ISSUE THREAD

**Issue by drone1** [VeliovGroup/flow-router#112]
### I'm having an issue:
  - Version of `flow-router-extra` you're experiencing this issue: 3.9.0 and 3.10.1
  - Version of `Meteor` you're experiencing this issue: 2.15
  - Browser name and its version (Chrome, Firefox, Safari, etc.)? Chrome Version 124.0.6367.119 (Official Build) (arm64)
  - Platform name and its version (Win, Mac, Linux)? Mac
  - If you're getting an error or exception, please provide its full stack-trace as plain-text or screenshot
  ```
[ostrio:flow-router-extra] [route.wait] Promise not resolved Error: Can't set timers inside simulations
    at withoutInvocation (meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:647:13)
    at bindAndCatch (meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:659:33)
    at Meteor.setTimeout (meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:674:21)
    at subWait (route.js:108:22)
    at route.js:128:11
    at meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:1343:22
```

This does not work for me:

methods.js (imported on both client and server):
```
// METEOR METHOD WITH CLIENT STUB
Meteor.methods({
	async 'simulation.test'() {
		if (Meteor.isServer) {
			const slowOperation = () => new Promise(resolve => Meteor.setTimeout(resolve, 1000))
			return await slowOperation()
		}
	}
})
```

routes.js, imported on the client:
```
FlowRouter.route('/', {
   		name: 'test',
		waitOn(params, query, ready) {
			return new Promise(async (resolve, reject) => {
				try {
					console.log('calling simulation.test...')
					await Meteor.callAsync('simulation.test')
					console.log('done.')
					resolve()
				} catch (err) {
					reject(err)
				}
			})
		},

		// ...action...
})
```

Exception thrown, since you are calling Meteor.setTimeout here:
```
    const subWait = (delay) => {
      timer = Meteor.setTimeout(() => {           // PROBLEM
        if (this.checkSubscriptions(subscriptions)) {
          Meteor.clearTimeout(timer);
          _data = getData();
          if (_resources) {
            whileWaitingAction();
            getResources();
          } else {
            next(current, _data);
          }
        } else {
          wait(24);
        }
      }, delay);
    };
```

If I change the Meteor method to have no client stub, the exception goes away:

(...routes.js same as above...)

methods.js
```
if (Meteor.isServer) {
	Meteor.methods({
		async 'simulation.test'() {
			const slowOperation = () => new Promise(resolve => Meteor.setTimeout(resolve, 1000))
			return await slowOperation()
		}
	})
}
```

Definiing waitOn() as follows instead does NOT seem to cause the exception:

```
			return new Promise((resolve, reject) => {   // NOTE: No 'async' here
				try {
					console.log('calling simulation.test...')
					Meteor.call('simulation.test', (err, result) => {    // NOTE: Meteor.call rather than 'await Meteor.callAsync'
						console.log('done.')
						resolve()
					})
				} catch (err) {
					reject(err)
				}
			})
```

Originally I was definiing waitOn() with ``return new Promise(async (resolve, reject) => ...`` and calling a ValidatedMethod, which always defines a client stub as far as I can tell, like ``await myValidatedMethod.callAsync()``, which caused this exception.

Would be great if you could support client stubs, but anyway, any suggestions here? Am I doing something unreasonable? Thanks.

**Comment by dr-dimitru** [comment]
@drone1 generally I'd say — Use stubs only for user-interaction actions.
What expected behavior you assuming when `waitOn` receives stub then server response, page/route reload?

**Comment by drone1** [comment]
Hey @dr-dimitru!

Maybe it would be helpful to throw an exception before Meteor.setTimeout() if in simulation? I'm not sure if this is an easy one-liner, since the code is running outside of a method, you may not be able to check ``isSimulation`` as you can within a Meteor method. Maybe not worth it.

The behavior I'd expect is to not get an exception thrown by Meteor.setTimeout() being called, and the code moving along as expected as data comes back from the server.

The Meteor docs recommend client stubs for all methods IIRC so I'd gotten into the habit of doing that.

Thanks for getting back.

**Comment by dr-dimitru** [comment]
@drone1 Do you want to push a PR?

**Comment by dr-dimitru** [comment]
@drone1 I tested it with `meteor@3` and 
```
blaze@3.0.1
blaze-html-templates@3.0.0
blaze-tools@2.0.0
```

all works as expected, no error thrown, please check at your end

**Comment by drone1** [comment]
I think you may have replied to the wrong thread here?

**Comment by dr-dimitru** [comment]
@drone1 no, I tested simulated "stub" Methods on client

**Comment by drone1** [comment]
> @drone1 no, I tested simulated "stub" Methods on client

Okay. I was saying that in the case I described it would be helpful if it threw an error, not that it threw an error.

**Comment by dr-dimitru** [comment]
@drone1 

> Originally I was definiing waitOn() with return new Promise(async (resolve, reject) => ... and calling a ValidatedMethod, which always defines a client stub as far as I can tell, like await myValidatedMethod.callAsync(), which caused this exception.
> 
> Would be great if you could support client stubs, but anyway, any suggestions here? Am I doing something unreasonable? Thanks.

You clearly mention exception in your original issue report, and asking to support "client stubs". Am I missing something here?

**Comment by drone1** [comment]
> Maybe it would be helpful to throw an exception before Meteor.setTimeout() if in simulation? I'm not sure if this is an easy one-liner, since the code is running outside of a method, you may not be able to check `isSimulation` as you can within a Meteor method. Maybe not worth it.

Ah sorry, I was referring to this.

**Comment by dr-dimitru** [comment]
@drone1 I need more details on what we are trying to fix here. As of now I do not understand. As far as I see if Method defined on Client and Server it means we want to run it as simulation, if not — it should get defined on Server only. Either way FlowRouter should accept any Promises in `waitOn` hook and wait for all to resolve, isn't it?

**Comment by drone1** [comment]
I’ll get you more details but this issue is super low priority IMO compared
to the other one I submitted where the yield breaks in Meteor 3 :)

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
