### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/flow-router#59]
- latest `flow-router-extra` package version (`3.6.0`)
 - latest `meteor` (`1.8.0.1`)

When trying to launch tests with:
```shell
meteor test-packages ./
```

End up looking at this exception:
```
$ meteor test-packages ./
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20181209-03:32:31.507(2)? (STDERR) /Users/user/.meteor/packages/promise/.0.11.2.17jdcpl.glsd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20181209-03:32:31.547(2)? (STDERR)       throw error;
W20181209-03:32:31.548(2)? (STDERR)       ^
W20181209-03:32:31.548(2)? (STDERR) 
W20181209-03:32:31.548(2)? (STDERR) Error: key $clusterTime must not start with '$'
W20181209-03:32:31.548(2)? (STDERR)     at Query.toBin (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/commands.js:146:25)
W20181209-03:32:31.549(2)? (STDERR)     at serializeCommands (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1045:43)
W20181209-03:32:31.549(2)? (STDERR)     at Pool.write (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1261:3)
W20181209-03:32:31.549(2)? (STDERR)     at executeWrite (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
W20181209-03:32:31.549(2)? (STDERR)     at WireProtocol.insert (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
W20181209-03:32:31.549(2)? (STDERR)     at Server.insert (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:815:35)
W20181209-03:32:31.550(2)? (STDERR)     at Server.insert (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
W20181209-03:32:31.550(2)? (STDERR)     at OrderedBulkOperation.finalOptionsHandler (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1003:25)
W20181209-03:32:31.550(2)? (STDERR)     at executeCommands (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:165:17)
W20181209-03:32:31.550(2)? (STDERR)     at executeOperation (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:420:24)
W20181209-03:32:31.550(2)? (STDERR)     at OrderedBulkOperation.execute (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:121:12)
W20181209-03:32:31.551(2)? (STDERR)     at bulkWrite (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:115:8)
W20181209-03:32:31.551(2)? (STDERR)     at executeOperation (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:420:24)
W20181209-03:32:31.551(2)? (STDERR)     at Collection.insertMany (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:528:10)
W20181209-03:32:31.551(2)? (STDERR)     at Collection.insert (/Users/user/.meteor/packages/npm-mongo/.3.1.1.1pjom2b.ao8o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:675:15)
W20181209-03:32:31.551(2)? (STDERR)     at MongoConnection._insert (packages/mongo/mongo_driver.js:373:16)
```

mb related: https://github.com/VeliovGroup/Meteor-Files-Demos/issues/13

**Comment by coagmano** [comment]
Just gave it a try and it works fine for me:

```
2018-12-10 14:23:23 - Freds-MacBook-Pro-2 in ~/development/flow-router-extra
± |detached:master ✓| → git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

2018-12-10 14:23:25 - Freds-MacBook-Pro-2 in ~/development/flow-router-extra
± |master → origin ✓| → git pull
Already up to date.

2018-12-10 14:24:02 - Freds-MacBook-Pro-2 in ~/development/flow-router-extra
± |master → origin ✓| → meteor --version
Meteor 1.8.0.1

2018-12-10 14:24:43 - Freds-MacBook-Pro-2 in ~/development/flow-router-extra
± |master → origin ✓| → meteor test-packages ./
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```
All tests pass in browser.

Was this on a particular branch or PR that they don't run?

**Comment by dr-dimitru** [comment]
Hey @coagmano ,

Thank you for testing this out 🎉
Going to re-install meteor itself...

**Comment by dr-dimitru** [comment]
fixed, idk why and how, maybe reboot

**Comment by dr-dimitru** [comment]
Spoke too soon.

Tests are failing unless I remove [this line](https://github.com/VeliovGroup/flow-router/blob/master/package.js#L29) and [this line](https://github.com/VeliovGroup/flow-router/blob/master/package.js#L43) excluding all `fast-render` tests.

@coagmano any ideas?

**Comment by dr-dimitru** [comment]
@coagmano looks like local mongodb error. Running tests on dedicated mongodb instance solve this issue.

MongoDB start script:
```
mongod --config ./conf.conf --fork
```

./conf.conf:
```
storage:
  dbPath: /mongodb
  journal:
    enabled: true
  engine: wiredTiger
systemLog:
  verbosity: 0
  traceAllExceptions: false
  destination: file
  quiet: true
  path: /mongod.log
net:
  port: 27017
  bindIp: 127.0.0.1
  unixDomainSocket:
    enabled: true
    filePermissions: 0777
operationProfiling:
  slowOpThresholdMs: 2100
  mode: off
```

My case test script:
```
MONGO_URL="mongodb://127.0.0.1:27017/testsmeteor4" ROOT_URL="http://127.0.0.1:3003" meteor test-packages ./ --port 3003
```
